//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.12 at 09:28:51 AM CEST 
//


package se.inkassogram.api.createinvoicebookkeeping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for foreignCustomerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="foreignCustomerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="country" minOccurs="0">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value="Sweden"/>
 *                 &lt;enumeration value="Norway"/>
 *                 &lt;enumeration value="Denmark"/>
 *                 &lt;enumeration value="Finland"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="countryWithNoSsnCheck" type="{http://www.inkassogram.se/API/createInvoiceBookkeeping}countryWithNoSsnCheckType" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "foreignCustomerType", propOrder = {
    "country",
    "countryWithNoSsnCheck"
})
public class ForeignCustomerType {

    protected String country;
    protected CountryWithNoSsnCheckType countryWithNoSsnCheck;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the countryWithNoSsnCheck property.
     * 
     * @return
     *     possible object is
     *     {@link CountryWithNoSsnCheckType }
     *     
     */
    public CountryWithNoSsnCheckType getCountryWithNoSsnCheck() {
        return countryWithNoSsnCheck;
    }

    /**
     * Sets the value of the countryWithNoSsnCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryWithNoSsnCheckType }
     *     
     */
    public void setCountryWithNoSsnCheck(CountryWithNoSsnCheckType value) {
        this.countryWithNoSsnCheck = value;
    }

}
