//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.12 at 09:28:52 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.inkassogram.se/API/creditInvoice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.inkassogram.api.creditinvoice;
